# Generated by Django 4.0.2 on 2022-06-05 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_folder', to='folders.folder')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.namegroup')),
            ],
            options={
                'unique_together': {('folder', 'name')},
            },
        ),
    ]
